let
    Source = #"PDF QUERY",
    AddedFromName = Table.AddColumn(Source, "ExportDateFromName",
        each fnExtractDateFromName([Source.Name]), type nullable date),
    MergedMeta = Table.NestedJoin(AddedFromName, {"Source.Name"}, FilesMeta, {"Source.Name"}, "Meta", JoinKind.LeftOuter),
    ExpandedMeta = Table.ExpandTableColumn(MergedMeta, "Meta", {"Date modified"}, {"Date modified"}),
    AddedExportDate = Table.AddColumn(ExpandedMeta, "ExportDate",
        each if [ExportDateFromName] <> null
             then [ExportDateFromName]
             else DateTime.Date([Date modified]),
        type date)
in
    AddedExportDate
